/*
  Warnings:

  - You are about to drop the column `body` on the `posts` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "posts" DROP COLUMN "body",
ADD COLUMN     "author" TEXT NOT NULL DEFAULT '映像求人PRO編集部',
ADD COLUMN     "h2_1_title" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h2_3_title" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h2_4_title" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h2_5_title" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_1_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_1_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_1_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_3_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_3_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_3_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_5_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_5_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "h3_5_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "lead" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "metaDescription" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "metaTitle" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "ogImage" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_1_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_1_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_1_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_3_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_3_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_3_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_4_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_4_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_5_1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_5_2" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "p_5_3" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "readingTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "relatedCategory" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tags" TEXT[],
ALTER COLUMN "title" SET DEFAULT '';
